version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello"
   job2:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: echo "From job2"
   job3:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: echo "From job3"
   job4:
     name: renamedjob4
     requires:
       - job3
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: echo "From job4"      
workflows:
    version: 2
    workflow1:
      jobs:
        - job2
    workflow2:
      jobs:
        - job3
 
