version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello"
   job2:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: ls -la ~/./ssh
       - add_ssh_keys
       - run: echo "From job2"
       - run: ls -la ~/./ssh
   job3:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: echo "From job3"
   job4:
     name: renamedjob4
     requires:
       - job3
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: env      
workflows:
    version: 2
    workflow1:
      jobs:
        - job2
 
