version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: ssh-add -l
       - checkout
       - run: echo "A first hello"
       - run: ls -la ~/.ssh
       - run: cat ~/.ssh/known_hosts
       - run: ssh-keygen -F myhost
   job2:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       #- run: ls -la ~/.ssh
       - run: ssh-add -l
       - add_ssh_keys
       - run: echo "From job2"
       - run: ls -la ~/.ssh
       - run: cat ~/.ssh/known_hosts
       - run: cat ~/.ssh/config
   job3:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: echo "From job3"
   job4:
     name: renamedjob4
     requires:
       - job3
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: env      
workflows:
    version: 2
    workflow1:
      jobs:
        - build
 
