version: 2.1
jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: ssh-add -l
       - checkout
       - run: echo "A first hello"
       - run: ls -la ~/.ssh
       - run: cat ~/.ssh/known_hosts
       - run: ssh -T -ai ~/.ssh/id_rsa git@github.com
   job2:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       #- run: ls -la ~/.ssh
       - run: ssh-add -l
       - add_ssh_keys
       - run: echo "From job2"
       - run: ls -la ~/.ssh
       - run: cat ~/.ssh/known_hosts
       - run: cat ~/.ssh/config
   job3a:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: echo "From job3a"
       - run: echo $(pwd) $CIRCLE_WORKING_DIRECTORY
   job3b:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: echo "From job3b"
       - run:
           command: echo $(pwd) $CIRCLE_WORKING_DIRECTORY
           name: 3b
           working_directory: /tmp
   job4:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: env
       - run:
           command: sleep 15
           no_output_timeout: 5s
   job5:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: echo "scheduled job5"
   job6:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - run: echo "job6"
workflows:
    version: 2
    workflow1:
      triggers:
        - schedule:
            cron: "4,6,8 * * * *"
            filters:
              branches:
                only: master
      jobs:
        - job5
    workflow2:
      jobs:
        - job6:
            name: job6a
            filters:
              branches:
                only: patate
        - job3b:
            filters:
              branches:
                only: master22          
        - job6:
            name: job6b
            requires:
              - job3b
            filters:
              branches:
                only: master
        - job6:
            name: job6c
            requires:
              - job6b
            filters:
              branches:
                only: master
     
